serve
`bash` is not guaranteed to be in `/bin`. Use the more portable `/usr/bin/env bash` instead.
=> Make serve script more portable

docs/access/vscode.md
you should set --name on tunnel or it'll use the first node ID but this name is persisted across sessions.
this info is store under ~/.vscode-server (this path can be changed with --cli-data-dir but I am not sure what happens when it gets [partially] deleted by the scratch policy...)
=> vscode --name

mkdocs.yml, overrides/main.html
Following https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/?h=ann#announcement-bar.
=> Add banner saying documentation is work in progress

docs/alps/hardware.md, docs/guides/internet-access.md, docs/software/container-engine.md, mkdocs.yml
Ports https://confluence.cscs.ch/spaces/KB/pages/868820917/Internet+access+on+the+Alps+infrastructure to the new docs. Currently under "Guides".
@bcumming do you think it makes sense to rename "Guides" already now or shall we keep it like this for now.
This section could fit close to the "Alps High Speed Network" section, but I think it's a bit too hidden to put it there. Additionally, I think it's good if the hardware is focused on the hardware itself and doesn't go into implementation details like this (i.e. that a proxy server is required for compute nodes).
=> Add internet access page

docs/alps/hardware.md, docs/index.md, docs/software/communication/cray-mpich.md, docs/software/communication/index.md, docs/software/communication/libfabric.md, docs/software/communication/nccl.md, docs/software/communication/openmpi.md, docs/software/communication/rccl.md, mkdocs.yml
Adds a "Communication Libraries" subtree next to scientific applications and others under "Software". I've populated the Cray MPICH page with information on using GPU-aware MPI and the known issues page from the old knowledge base. Other pages (OpenMPI, NCCL, RCCL, and libfabric) are mostly stubs at the moment.
=> Start "Communication Libraries" section

.github/CODEOWNERS
Adds a `CODEOWNERS` file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners.
The main benefit (IMO) is that the "code owners" for a particular file/path will automatically get requested for reviews whenever those files are changed. This means that the relevant people will automatically be at least informed about the changes.
Note that this doesn't prevent others from giving/being requested to do reviews. This just sets the default.
At the same time I think this is a good way to encode in the git repo itself who is "responsible" for the documentation for whatever definition of "responsible" we want to agree on.
I've started with the most minimal set of code owners that I could think of. I'm happy to be a …
=> Add first version of `CODEOWNERS` file

docs/software/communication/cray-mpich.md, docs/software/sciapps/cp2k.md
It's set by default on daint (to a different value).
Only reason to keep it here is if we expect many users to be running CP2K on other clusters, but then I'd rather make sure `CUDA_CACHE_PATH` is set by default there instead?
=> Better document `CUDA_CACHE_PATH` in CP2K docs

docs/software/prgenv/prgenv-gnu.md, docs/software/prgenv/prgenv-nvfortran.md
These are a cut and paste, and slight upgrade over the originals in the alps-uenv docs.
Still not fully complete, but better than before.
=> add prgenv-[gnu,nvfortran] docs

docs/guides/gb2025.md, mkdocs.yml
I am going to push these immediately, so that others can push their contributions in time for making the system public this afternoon.
=> document affinity and openmp fixes for GB runs

docs/access/vscode.md, docs/guides/terminal.md, mkdocs.yml
Add some terminal documentation:
* default shells
* configuring your environment for HOME mounted on multiple architectures
Quick link to the new page: https://docs.tds.cscs.ch/65/guides/terminal/
=> add terminal docs

docs/software/prgenv/index.md, docs/software/prgenv/prgenv-gnu.md
* add docs for prgenv-gnu/24.11:v2
* add an index page for the programming environment section
=> docs for prgenv-gnu/24.11:v2

docs/build-install/uenv.md
I think the current description of the `spack` view is misleading. I tried to improve things, trying to make clear that the `spack` view sets some environment variables that are _not_ automatically used by Spack.
=> Clarify uenv spack view

docs/software/sciapps/quantumespresso.md
Preview: https://docs.tds.cscs.ch/69/software/sciapps/quantumespresso/
=> Update QuantumESPRESSO documentation

docs/software/sciapps/quantumespresso.md
Add the suggestions from @RMeli in the previous PR
=> update QE doc

docs/access/mfa.md, docs/clusters/clariden.md, docs/clusters/santis.md, docs/contributing/index.md, docs/guides/gb2025.md, docs/guides/terminal.md, docs/software/container-engine.md, docs/software/devtools/linaro-ddt.md, docs/software/devtools/linaro-forge.md, docs/software/prgenv/prgenv-gnu.md, docs/software/prgenv/prgenv-nvfortran.md, docs/software/uenv.md, docs/storage/object.md, readme.md
I've attempted to fix up some code blocks. Whatever was obviously a terminal (ehm, console) session I've updated to use `console`. Turns out `terminal` isn't a valid lexer, and just does no highlighting. I've changed some types to `bash` or `console` a bit depending on the contents of the code block, but I have not tried to fix everything.
I've added a section about code blocks to the style guide, which we can try to follow when updating existing or adding new docs.
=> Update code blocks and add guidelines on usage to style guide

docs/guides/gb2025.md
Low noise mode is still active, just in a reduced form. Updates the GB page to reflect this. I've also moved the warning about not being able to allocate all 72 cores to the `SLURM` subsection.
=> Minor updates to GB low noise mode description

.github/CODEOWNERS, docs/guides/gb2025.md, docs/software/communication/cray-mpich.md, docs/software/communication/libfabric.md, docs/software/communication/nccl.md, docs/software/communication/openmpi.md, docs/software/communication/rccl.md, docs/software/container-engine.md, docs/software/sciapps/quantumespresso.md
Adds a bit more text to the libfabric, OpenMPI, NCCL, and RCCL pages. Still far from complete, but another step forward hopefully.
=> Expand communication pages

docs/services/firecrest.md
Given that v1 is on deprecation mode:
- added deprecation notice in a `warning` block
- removed bottom links to v1
- changed/fixed URLs
=> Added deprecation notice for v1

.github/actions/spelling/block-delimiters.list, .github/workflows/spelling.yaml
I also added a generic html comment marker that can be used to ignore full blocks of text (which won't show up in the rendered output because it's an html comment).
The feature seems very early, and likely to change, but I've pinned the commit, so it should keep working this way until we update the action. It's based on this commit: https://github.com/check-spelling/check-spelling/commit/46c981b7c96b3777aff4fd711fc9a8f126121b04.
=> Ignore code blocks from spell checking

docs/software/communication/openmpi.md
=> Fix missing code block end in OpenMPI docs

docs/software/prgenv/prgenv-nvfortran.md
pull a version followed by uenv image find instead of uenv image pull
=> typo in nvfortran docs

docs/platforms/cwp/index.md
Santis will still be under UMP for some time, which should be reflected by the documentation.
=> Change CWP docs to point to UMP

docs/storage/filesystems.md
A few minor style nits from #121.
=> Minor fixes to storage docs

docs/contributing/index.md
I added a link to the GitHub official guide page about updating files on the web in the "Small contributions" section.
=> Link the GitHub guide for a small change

docs/software/communication/nccl.md, docs/software/communication/nccl_env_vars, docs/software/ml/pytorch.md, mkdocs.yml
Based on https://github.com/eth-cscs/cscs-docs/pull/146#issuecomment-2949210456. This adds NCCL environment variables to a separate file and includes it in both the NCCL and pytorch sections.
@boeschf @RMeli could you let me know what you think of this? The bash comments are definitely uglier, but perhaps not too bad. They show up in both sections. I've removed the explicit `MPICH_GPU_SUPPORT_ENABLED=0` from the NCCL side, but it's still mentioned in a warning (as before). The pytorch side still has `MPICH_GPU_SUPPORT_ENABLED=0` explicitly.
=> Use one source of truth for NCCL environment variables

docs/contributing/index.md
For users who desire to contribute continuously (e.g., some CSCS staff), they might already have their own fork repository. This PR added a small heads-up (or tip) on the contribution page to sync the fork repository before proceeding.
=> Add heads-up to sync the fork repository

docs/clusters/bristen.md, docs/clusters/clariden.md, docs/clusters/santis.md, docs/contributing/index.md, docs/guides/mlp_tutorials/llm-finetuning.md, docs/guides/mlp_tutorials/llm-inference.md, docs/running/jobreport.md, docs/services/firecrest.md, docs/software/communication/cray-mpich.md, docs/software/ml/pytorch.md, docs/software/sciapps/gromacs.md, docs/software/sciapps/lammps.md, docs/software/sciapps/vasp.md, docs/software/uenv/index.md
With #148 it is suggested to rename `SLURM` -> `Slurm`. This is an accompanying PR to change it also on every other page for consistency.
=> SLURM -> Slurm

docs/software/ml/pytorch.md
optionally add warning somewhere?
=> Avoid port 6000 in pytorch

.github/workflows/docs_merge_queue.yaml
This adds a workflow that is triggered on the `merge_group` event. I went for a separate workflow to keep things straightforward (avoiding conditional steps etc. in other workflows), but I'm happy to try to integrate it into one of the existing workflows as well if you think that's better.
Please do not merge as is, I'd like to make sure this can be successfully merged through the merge queue.
=> Add workflow for merge queue

.github/actions/spelling/allow.txt, docs/contributing/index.md
Updating contributing guide:
- Change order in "Getting started" section to promote self-review before push
- Clarify Review Process section, confusing use of owner term?
- Images: screenshots vs diagrams, promoting diagrams as code :)
Fun facts worth noting:
- The contributing guide for updating the contributing guide is the same contributing guide
- Some contributions to the contributing guide could eventually be both a violation and an improvement of the guide
=> Improving contributing guide

docs/services/cicd.md
@egparedes is about to modify the gt4py pipeline, and I'd like to link to their project for the `dynamic-image-name` block as an example.
=> add GT4Py as example project using dynamic-image-name

docs/services/cicd.md
All changes from the `alps` branch have already been merged into `main`.
=> Fix outdated reference to alps branch on cscs-reframe-tests repo

docs/services/cicd.md
This PR adds the missing information that was available on the old KB, and not ported fully to this docs.
=> add missing information how to API trigger on PR/tag/SHA

docs/software/sciapps/cp2k.md
Document a workaround to avoid crashes with older CP2K uenvs on Eiger.Alps (which appeared after the migration).
=> Document new issue with older CP2K uenvs in Eiger

docs/software/sciapps/cp2k.md
I have a strong feeling that many users do not read the full CP2K documentation and miss the important `Known issues` section. This leads to sub-optimal runs and waste of resources. This should hopefully help.
=> Add clear reminder to check known issues with CP2K

docs/software/container-engine/run.md
There was a misunderstanding from my side when I wrote this documentation. This PR fixes this misunderstanding.
=> Revise the `--environment` usage with the default EDF search path.

docs/services/cicd.md
The title of `uenv-builder` was mistakenly named `uenv-runner`.
=> fix uenv-runner --> uenv-builder

.github/actions/spelling/allow.txt, docs/software/communication/mpich.md, mkdocs.yml
This documentation is adding a reference how to build a container with MPICH, that allows native communication speeds.
Both GPU and CPU examples are included.
No example for building outside of a container is provided (but it surely would be possible to build directly baremetal, it is however untested)
=> add MPICH communication docs

docs/index.md, overrides/main.html
Small readbility improvements for users who land on the main index page.
* remove the banner that links to the old KB - this hasn't generated any tickets, and we have had enough time for users to get used to the new site
* reduce text and add centering to the link to the status page at the top of the main index page to reduce clutter
=> Remove kb banner and align status.cscs.ch box

.github/actions/spelling/allow.txt, .github/actions/spelling/patterns.txt, docs/contributing/index.md
Updated the contributing guide to provide more information about the core team, and where the "rules and regulations" come from.
Also cover why screenshots should be avoided unless they really add something to the docs.
The new section: https://docs.tds.cscs.ch/247/contributing/#before-starting
=> explain core team and update image policy

docs/software/container-engine/known-issue.md, docs/software/container-engine/run.md
Resolves: [VCUE-1014](https://jira.cscs.ch/browse/VCUE-1014)
As specifying "--environment" as an "#SBATCH" option has caused many nonsensical problems, the container team decided to add an explicit warning (alongside some mitigations to known errors). To avoid distraction, the warning message was kept short in the main usage page ("Using container engine") and linked to the main warning message ("Known issues").
=> Add a warning message about "--environment in SBATCH"

docs/policies/index.md, docs/policies/maintenance.md, docs/policies/support.md, mkdocs.yml
I provide an update of the policies as described in [SRM-274](https://jira.cscs.ch/browse/SRM-274) in view of the presentation "General Information for Users on Alps" at the UserLab Day 2025.
=> Update policies introducing maintenance policies

.github/CONTRIBUTING.md, .github/workflows/welcome.yaml
- Adds a `CONTRIBUTING.md` file (which simply links to the contributing guidelines in the docs) to improve visibility. The `CONTRIBUTING.md` file is shown on the main repo page.
- Adds a first-interaction github workflow which also guides contributors to the guidelines in case they missed the guidelines before opening a PR. A comment with a link to the guidelines is posted on PRs from first-time contributors.
=> Make contributing guidelines more visible

.github/actions/spelling/expect.txt, docs/software/ml/index.md
this could very well grown to a full page with recommendations for IO profiling and monitoring tools
but I don't think we have much ready at the moment, so we could very well take this as it is now and revisit it in the future?
=> ML storage

docs/running/slurm.md
fixes to the upstream repo not included..
=> Update build instructions for affinity GPU backend

docs/build-install/uenv.md
The documentation section was using both `<build-path>` and `<build-dir>`. This makes it unclear that they are both referring to the same string.
Here we choose to consistently use `<build-path>`, since it is a path to a directory.
=> 📚 Build-uenv: consistently use `<build-path>`
